<?php
/** Source-only native refresh composed regression. No WP bootstrap/site DB/installed-state proof. */
error_reporting(E_ALL); ini_set('display_errors','0'); ini_set('log_errors','0');
$owner=dirname(__DIR__,2); $endpoint=__DIR__.'/cart-session-lifecycle-integration-fixture.php';
$files=['operation'=>$owner.'/includes/utils/class-cart-session-operation.php','fixture'=>$endpoint,'refresh-fixtures'=>__DIR__.'/cart-session-native-refresh-fixtures.php','adapter'=>__DIR__.'/cart-session-owned-handler-fixtures.php','handler'=>$owner.'/includes/utils/class-ql-session-handler.php','lifecycle'=>$owner.'/includes/utils/class-cart-session-lifecycle.php','storage'=>$owner.'/includes/utils/class-cart-session-storage.php','HTTP'=>$owner.'/includes/utils/class-cart-session-http-boundary.php'];
$native=rtrim(getenv('WL_HEADLESS_LOGIN_SOURCE')?:'','/');
$native_paths=['WPGraphQL\\Login\\Mutation\\RefreshToken'=>'/src/Mutation/RefreshToken.php','WPGraphQL\\Login\\Auth\\TokenManager'=>'/src/Auth/TokenManager.php','WPGraphQL\\Login\\Auth\\User'=>'/src/Auth/User.php','WPGraphQL\\Login\\Utils\\Utils'=>'/src/Utils/Utils.php','WPGraphQL\\Login\\Vendor\\Firebase\\JWT\\JWT'=>'/vendor-prefixed/firebase/php-jwt/src/JWT.php','WPGraphQL\\Login\\Vendor\\Firebase\\JWT\\Key'=>'/vendor-prefixed/firebase/php-jwt/src/Key.php','native-server-auth'=>'/src/Auth/ServerAuthentication.php','native-refresh-base'=>'/vendor-prefixed/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/MutationType.php','native-refresh-base-type'=>'/vendor-prefixed/axepress/wp-graphql-plugin-boilerplate/src/Abstracts/Type.php','native-jwt-expired'=>'/vendor-prefixed/firebase/php-jwt/src/ExpiredException.php','native-jwt-before-valid'=>'/vendor-prefixed/firebase/php-jwt/src/BeforeValidException.php','native-jwt-signature-invalid'=>'/vendor-prefixed/firebase/php-jwt/src/SignatureInvalidException.php'];
foreach($native_paths as $name=>$file){$files[$name]=$native.$file;}
$files['WP_Hook']=rtrim(getenv('WL_WORDPRESS_SOURCE')?:'','/').'/wp-includes/class-wp-hook.php';
$files['plugin.php']=rtrim(getenv('WL_WORDPRESS_SOURCE')?:'','/').'/wp-includes/plugin.php';
foreach(['InstrumentSchema'=>'/src/Utils/InstrumentSchema.php','WPMutationType'=>'/src/Type/WPMutationType.php','ExecutionResult'=>'/vendor/webonyx/graphql-php/src/Executor/ExecutionResult.php']as $name=>$file){$files[$name]=rtrim(getenv('WL_WPGRAPHQL_SOURCE')?:'','/').$file;}
$pins=json_decode(file_get_contents(__DIR__.'/cart-session-native-refresh-pins.json'),true,512,JSON_THROW_ON_ERROR);
foreach($pins as $name=>$pin){ if(!isset($files[$name])||!is_file($files[$name])||!hash_equals($pin,hash_file('sha256',$files[$name]))){fwrite(STDERR,'Refresh source pin mismatch: '.$name.PHP_EOL);exit(2);} }
foreach(['WL_WORDPRESS_SOURCE'=>'/wp-includes/plugin.php','WL_WOOCOMMERCE_SOURCE'=>'/includes/class-wc-session-handler.php','WL_WPGRAPHQL_SOURCE'=>'/vendor/autoload.php','WL_MU_PLUGINS_SOURCE'=>'/database/interface-owned-scope-driver.php','WL_HEADLESS_LOGIN_SOURCE'=>'/src/Mutation/RefreshToken.php']as $env=>$file){if(!is_file(rtrim(getenv($env)?:'','/').$file)){fwrite(STDERR,'Missing refresh integration native source input.'.PHP_EOL);exit(2);}}
foreach(['fixture'=>'WL_INTEGRATION_FIXTURE_SHA','refresh-fixtures'=>'WL_REFRESH_FIXTURE_SHA','adapter'=>'WL_INTEGRATION_ADAPTER_SHA','handler'=>'WL_INTEGRATION_HANDLER_SHA','operation'=>'WL_INTEGRATION_OPERATION_SHA','lifecycle'=>'WL_INTEGRATION_LIFECYCLE_SHA'] as $name=>$env){putenv($env.'='.$pins[$name]);}
putenv('WL_REFRESH_NATIVE_SOURCES='.json_encode(array_intersect_key($pins,$native_paths),JSON_THROW_ON_ERROR));
putenv('WL_INTEGRATION_RESULT_SHA=899f37cf608b43eddba734604ba301e178b02f7bf12edf0b8b920b4053435fd9');
$before=array_map(fn($file)=>hash_file('sha256',$file),$files); $total=0;$failures=0;
function expect_refresh($condition){if(!$condition){throw new RuntimeException('Sanitized refresh assertion failed.');}}
function refresh_child($case,$bearer=null){global $endpoint; if (null!==$bearer) {putenv('WL_REFRESH_BEARER='.$bearer);} $ledger=tempnam(sys_get_temp_dir(),'wl-native-refresh-');chmod($ledger,0600);try{$process=proc_open([PHP_BINARY,'-d','display_errors=0','-d','log_errors=0','-d','output_buffering=0',$endpoint,$case,$ledger],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);expect_refresh(is_resource($process));fclose($pipes[0]);$body=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($process);$state=json_decode(file_get_contents($ledger),true);expect_refresh(0===$code&&''===$err&&is_array($state));return[json_decode($body,true),$state];}finally{unlink($ledger);}}
function refresh_case($name,$action){global$total,$failures;$total++;try{$action();echo'PASS '.$name.PHP_EOL;}catch(Throwable$e){$failures++;echo'FAIL '.$name.' [sanitized assertion or boundary failure]'.PHP_EOL;}}
function refresh_preserved($state,$allow_inert_customer=false){expect_refresh(true===$state['terminal']&&0===$state['writes']&&true===$state['row_preserved']&&true===$state['markers_preserved']&&true===$state['orders_preserved']&&true===$state['non_auth_meta_preserved']);foreach(['customer.save','cart.set_session','cart.persistent','cart.cookies','cart.calculate','db-write','timestamp-write','cache-write','cookie-emitted','token-built']as$event){if ($allow_inert_customer && 'customer.save'===$event) {continue;} expect_refresh(!in_array($event,$state['events'],true));}}
foreach(['refresh-success','refresh-cart-token','refresh-same-actor','refresh-alias-fragment','refresh-variable-directives']as$case){refresh_case($case.' actual native renewal releases before identity',function()use($case){[$response,$state]=refresh_child($case);refresh_preserved($state);$result=$response['data']['refreshToken']??$response['data']['renewed']??null;expect_refresh(true===($result['success']??$result['ok']??null)&&is_string($result['authToken']??$result['token']??null)&&ctype_digit($result['authTokenExpiration']??$result['expires']??''));expect_refresh(!isset($response['errors'])&&('refresh-same-actor'===$case?17:23)===$state['actor']&&true===$state['detached']&&true===$state['refresh_detached_before_identity']&&true===$state['refresh_authority_cleared']);expect_refresh(['graphql_login_token_expiration']===$state['meta_write_keys']&&1===count(array_filter($state['calls'],fn($c)=>'release'===$c)));});}
foreach(['refresh-invalid','refresh-invalid-authenticated','refresh-expired','refresh-revoked','refresh-wrong-secret']as$case){refresh_case($case.' genuine native failure retains starting identity',function()use($case){[$response,$state]=refresh_child($case);refresh_preserved($state);expect_refresh(false===($response['data']['refreshToken']['success']??null)&&null===($response['data']['refreshToken']['authToken']??null)&&null===($response['data']['refreshToken']['authTokenExpiration']??null));expect_refresh(!isset($response['errors'])&&('refresh-invalid-authenticated'===$case?17:0)===$state['actor']&&true===$state['detached']&&[]===$state['meta_write_keys']&&!in_array('native.identity-change',$state['events'],true));});}
foreach(['refresh-mixed-first','refresh-mixed-last','refresh-two-aliases','refresh-login','refresh-logout','refresh-forbidden-user','refresh-forbidden-customer','refresh-forbidden-cart','refresh-forbidden-session']as$case){refresh_case($case.' rejects before native or cart effects',function()use($case){[$response,$state]=refresh_child($case);refresh_preserved($state);expect_refresh(['errors']===array_keys($response)&&'WL_CART_SESSION_TRANSITION_INVALID'===($response['errors'][0]['extensions']['code']??null));expect_refresh(!in_array('native.refresh-input',$state['events'],true)&&!in_array('native.identity-change',$state['events'],true)&&!in_array('callback.addToCart',$state['events'],true)&&[]===$state['meta_write_keys']);});}
foreach(['refresh-final-input-token','refresh-final-input-drift','refresh-different-actor','refresh-postcallback-drift','refresh-missing-success','refresh-empty-token','refresh-string-expiration','refresh-zero-expiration','refresh-false-with-token','refresh-false-with-expiration','refresh-no-actor','refresh-string-success','refresh-null-expiration','refresh-wrong-source','refresh-missing-source','refresh-wrong-factory','refresh-missing-factory','refresh-pre-substitution','refresh-batch','refresh-wrong-payload-type']as$case){refresh_case($case.' withholds contradictory native result',function()use($case){[$response,$state]=refresh_child($case);refresh_preserved($state);expect_refresh(['errors']===array_keys($response)&&'WL_CART_SESSION_TRANSITION_INVALID'===($response['errors'][0]['extensions']['code']??null)); if (in_array($case,['refresh-wrong-source','refresh-missing-source','refresh-wrong-factory','refresh-missing-factory','refresh-pre-substitution','refresh-batch','refresh-final-input-token','refresh-final-input-drift','refresh-wrong-payload-type'],true)) {expect_refresh(!in_array('native.identity-change',$state['events'],true)&&!in_array('replacement.refresh',$state['events'],true)&&[]===$state['meta_write_keys']);} });}
foreach(['refresh-storage-failure','refresh-cohort-drift','refresh-invalid-cart']as$case){refresh_case($case.' retains admission/storage/cohort refusal',function()use($case){[$response,$state]=refresh_child($case);refresh_preserved($state,'refresh-invalid-cart'===$case);expect_refresh(['errors']===array_keys($response)&&('refresh-invalid-cart'===$case?'WL_CART_SESSION_INVALID':'WL_CART_SESSION_UNAVAILABLE')===($response['errors'][0]['extensions']['code']??null));});}
refresh_case('separate ordinary viewer verifies new JWT actor without carried guest cart',function(){
    [$renewal,$renewal_state]=refresh_child('refresh-viewer-seed');refresh_preserved($renewal_state);
    $token=$renewal['data']['refreshToken']['authToken']??null;expect_refresh(is_string($token));
    [$viewer,$state]=refresh_child('refresh-fresh-viewer',$token);
    expect_refresh(!isset($viewer['errors'])&&17===($viewer['data']['viewer']['databaseId']??null)&&17===$state['actor']);
    expect_refresh(false===$state['carried_cart_header']&&true===$state['bearer_preserved']&&false===$state['detached']&&true===$state['row_preserved']&&true===$state['markers_preserved']&&true===$state['orders_preserved']);
    expect_refresh(!in_array('native.identity-change',$state['events'],true)&&[]===$state['meta_write_keys']);
});
refresh_case('expired Bearer preserves native WP_Error status without stripping or retry',function(){
    [$response,$state]=refresh_child('refresh-expired-bearer');
    expect_refresh('invalid-secret-key'===$state['native_auth_error']&&403===$state['native_status']&&0===$state['actor']&&true===$state['bearer_preserved']);
    expect_refresh(false===$state['carried_cart_header']&&false===$state['detached']&&[]===$state['meta_write_keys']&&!in_array('native.refresh-input',$state['events'],true));
    expect_refresh(true===$state['row_preserved']&&true===$state['orders_preserved']);
});
if (in_array('--http',$argv,true)) {
    $socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);expect_refresh(false!==$socket);
    $address=stream_socket_get_name($socket,false);fclose($socket);
    $ledger=tempnam(sys_get_temp_dir(),'wl-native-refresh-http-');chmod($ledger,0600);putenv('WL_INTEGRATION_HTTP_LEDGER='.$ledger);
    $server=proc_open([PHP_BINARY,'-d','display_errors=0','-d','log_errors=0','-d','output_buffering=0','-S',$address,$endpoint],[0=>['pipe','r'],1=>['file','/dev/null','a'],2=>['file','/dev/null','a']],$pipes);
    try {
        expect_refresh(is_resource($server));fclose($pipes[0]);$ready=false;
        for($attempt=0;$attempt<100;$attempt++){$connection=@stream_socket_client('tcp://'.$address,$errno,$error,0.1);if($connection){fclose($connection);$ready=true;break;}usleep(20000);}expect_refresh($ready);
        foreach(['refresh-success'=>200,'refresh-invalid'=>200,'refresh-mixed-first'=>200,'refresh-postcallback-drift'=>200,'refresh-storage-failure'=>503,'refresh-expired-bearer'=>403]as$case=>$status){
            refresh_case($case.' source HTTP preserves status and withholds cart credentials',function()use($address,$case,$status){
                $body=file_get_contents('http://'.$address.'/?case='.$case,false,stream_context_create(['http'=>['ignore_errors'=>true,'timeout'=>5]]));
                $headers=$http_response_header??[];$map=[];expect_refresh(str_contains($headers[0]??'',' '.$status.' '));
                foreach(array_slice($headers,1)as$header){$parts=explode(':',$header,2);if(2===count($parts)){$map[strtolower($parts[0])][] =trim($parts[1]);}}
                expect_refresh(['synthetic-auth']===($map['authorization']??[]));
                if ('refresh-expired-bearer'!==$case) {expect_refresh(!isset($map['woocommerce-session'])&&['unrelated=preserved; Path=/']===($map['set-cookie']??[]));}
                $response=json_decode($body,true);expect_refresh(is_array($response));
                if ('refresh-success'===$case){expect_refresh(true===($response['data']['refreshToken']['success']??null)&&is_string($response['data']['refreshToken']['authToken']??null));}
                elseif ('refresh-invalid'===$case){expect_refresh(false===($response['data']['refreshToken']['success']??null)&&null===($response['data']['refreshToken']['authToken']??null));}
                elseif ('refresh-expired-bearer'!==$case){expect_refresh(['errors']===array_keys($response));}
            });
        }
    } finally {if(is_resource($server)){proc_terminate($server);proc_close($server);}unlink($ledger);}
}
refresh_case('source cohort remains unchanged',fn()=>expect_refresh($before===array_map(fn($file)=>hash_file('sha256',$file),$files)));
echo'RESULT '.$total.' cases, '.$failures.' failures'.PHP_EOL;echo'PHP '.PHP_VERSION.PHP_EOL;foreach($before as$name=>$hash){echo'SOURCE '.$name.'-sha256='.$hash.PHP_EOL;}exit($failures?1:0);
