<?php
require __DIR__.'/bootstrap.php';
use WPGraphQL\WooCommerce\Utils\QL_Session_Handler;
use WPGraphQL\WooCommerce\Utils\Cart_Session_Lifecycle;
$case=$argv[1]??'';$ledger=$argv[2]??'';$GLOBALS['modern_case']=$case;require __DIR__.'/callbacks.php';add_filter('graphql_woocommerce_cart_session_signed_token','modern_cart_token_observer',10,1);
$GLOBALS['modern_meta']=[17=>['last_update'=>'','billing_city'=>'Stored city','billing_address_1'=>'Stored address','_woocommerce_persistent_cart_1'=>['sentinel'=>true],'graphql_login_secret'=>'fixture-user-secret','graphql_login_secret_revoked'=>false,'graphql_login_refresh_token_expiration'=>time()+86400],23=>['graphql_login_secret'=>'fixture-user-secret','graphql_login_secret_revoked'=>false,'graphql_login_refresh_token_expiration'=>time()+86400]];
HandlerContractBoundary::$user='refresh-guest-success'===$case?0:17;HandlerContractBoundary::$graphql=true;$GLOBALS['modern_starting_actor']=HandlerContractBoundary::$user;
HandlerContractBoundary::$woocommerce=(object)['session'=>null,'customer'=>null,'cart'=>null];
HandlerContractBoundary::$rows=['17'=>['cart'=>[]],'t_'.str_repeat('a',30)=>['cart'=>['native-sentinel'=>true]]];
HandlerContractBoundary::$cache=[WC_SESSION_CACHE_GROUP.':wc_'.WC_SESSION_CACHE_GROUP.'_cache_prefix'=>'fixed-prefix'];
$GLOBALS['wpdb']=$db=new HandlerContractDatabase();$_SERVER['REQUEST_METHOD']='POST';
$GLOBALS['modern_markers_before']=HandlerContractBoundary::$markers;$initial_rows=HandlerContractBoundary::$rows;$initial_meta=$GLOBALS['modern_meta'];
$GLOBALS['modern_meta_initial']=$initial_meta;modern_metadata_checkpoint();set_exception_handler('modern_previous_exception_handler');
$GLOBALS['modern_success']=false;$GLOBALS['modern_detail']=[];
register_shutdown_function(static function()use($ledger,$initial_rows,$initial_meta,$db){
 try {if($GLOBALS['modern_do_shutdown']??false){$GLOBALS['modern_shutdown_dispatched']=true;do_action('shutdown');}}catch(Throwable$e){$GLOBALS['modern_shutdown_error']=$e->getMessage();}
 $included=[];$loaded=[];foreach(get_included_files()as$file){$included[$file]=hash_file('sha256',$file);if(str_starts_with($file,getenv('WL_MODERN_AUTH_SOURCE_ROOT').'/')){$loaded[substr($file,strlen(getenv('WL_MODERN_AUTH_SOURCE_ROOT'))+1)]=hash_file('sha256',$file);}}
 file_put_contents($ledger,json_encode(['diagnostics'=>$GLOBALS['modern_diagnostics'],'success'=>$GLOBALS['modern_success'],'detail'=>$GLOBALS['modern_detail'],'events'=>HandlerContractBoundary::$events,'writes'=>$db->writes,'reads'=>$db->reads,'calls'=>$db->calls,'rows'=>HandlerContractBoundary::$rows,'meta'=>$GLOBALS['modern_meta'],'meta_initial'=>$GLOBALS['modern_meta_initial'],'meta_before'=>$GLOBALS['modern_meta_before'],'issued_token'=>$GLOBALS['modern_issued_token']??null,'response_status'=>http_response_code(),'previous_handler_called'=>$GLOBALS['modern_previous_handler_called']??0,'lifecycle_terminal'=>isset($GLOBALS['modern_handler'])&&$GLOBALS['modern_handler']->get_owned_lifecycle()?$GLOBALS['modern_handler']->get_owned_lifecycle()->is_terminal():null,'owned_scope'=>isset($GLOBALS['modern_handler'])?$GLOBALS['modern_handler']->has_owned_scope():false,'driver_state'=>$db->state,'shutdown_dispatched'=>$GLOBALS['modern_shutdown_dispatched']??false,'markers_preserved'=>$GLOBALS['modern_markers_before']===HandlerContractBoundary::$markers,'rows_preserved'=>$initial_rows===HandlerContractBoundary::$rows,'meta_preserved'=>$initial_meta===$GLOBALS['modern_meta'],'included'=>$included,'loaded'=>$loaded,'shutdown_error'=>$GLOBALS['modern_shutdown_error']??null,'hook_inventory'=>array_map(static function($h){$out=[];foreach($h->callbacks as$priority=>$entries){foreach($entries as$entry){$c=$entry['function'];$out[]=['priority'=>$priority,'args'=>$entry['accepted_args'],'callback'=>is_array($c)?[(is_object($c[0])?get_class($c[0]):$c[0]),$c[1]]:(is_string($c)?$c:'closure')];}}return $out;},$GLOBALS['wp_filter']),'error'=>$GLOBALS['modern_error']??null],JSON_THROW_ON_ERROR));
});
function modern_finish($detail=[]){$GLOBALS['modern_success']=true;$GLOBALS['modern_detail']=$detail;echo json_encode(['ok'=>true]);}
function modern_refused(callable$fn,$code='WL_CART_SESSION_UNAVAILABLE'){
 try{$fn();}catch(\GraphQL\Error\UserError$e){modern_expect(($e->getExtensions()['code']??null)===$code,'expected refusal code');return;}throw new RuntimeException('expected refusal');
}
try {
 if('expired-bearer'===$case){$token=\WPGraphQL\Login\Vendor\Firebase\JWT\JWT::encode(['iss'=>get_bloginfo('url'),'iat'=>time()-600,'nbf'=>time()-600,'exp'=>time()-120,'data'=>['user'=>['id'=>17]]],GRAPHQL_LOGIN_JWT_SECRET_KEY,'HS256');$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$token;$before=$_SERVER['HTTP_AUTHORIZATION'];$error=\WPGraphQL\Login\Auth\TokenManager::validate_token();modern_expect(is_wp_error($error)&&'invalid-secret-key'===$error->get_error_code()&&403===apply_filters('graphql_response_status_code',200)&&$before===$_SERVER['HTTP_AUTHORIZATION'],'native expired Bearer status and preservation');modern_finish(['native_status'=>403,'actor'=>get_current_user_id()]);return;}
 if('native-cookie'===$case){
  HandlerContractBoundary::$graphql=false;$parent=new WC_Session_Handler();WC()->session=$parent;$guest='t_'.str_repeat('a',30);$exp=(string)(time()+86400);$expiring=(string)(time()+3600);$hash=(new ReflectionMethod(WC_Session_Handler::class,'hash'))->invoke($parent,$guest.'|'.$exp);$_COOKIE['wp_woocommerce_session_'.COOKIEHASH]=$guest.'|'.$exp.'|'.$expiring.'|'.$hash;
  add_action('woocommerce_guest_session_to_user_id',static function($from,$to){modern_event('native-migration',[$from,$to]);},10,2);
  $parent->init();modern_expect('17'===$parent->get_customer_id()&&['native-sentinel'=>true]===$parent->get('cart'),'native parent migrated sentinel');modern_expect(!isset(HandlerContractBoundary::$rows[$guest])&&['native-sentinel'=>true]===HandlerContractBoundary::$rows['17']['cart'],'native migration rows');modern_expect(1===HandlerContractBoundary::count(['timestamp-write'])&&1===HandlerContractBoundary::count(['cookie-emitted']),'native migration timestamp/cookie controls');modern_finish();return;
 }
 if('seam-meta'===$case){$v="O'Reilly\\lane";update_user_meta(17,'fixture',wp_slash($v));modern_expect($v===get_user_meta(17,'fixture',true),'slash boundary roundtrip');modern_metadata_opponent(17,'fixture','new');modern_expect(false===update_user_meta(17,'fixture','stale','old'),'CAS boundary');modern_finish();return;}
 if(str_starts_with($case,'activity-')){
  $mode=substr($case,9);$ago=match($mode){'default-skip'=>59,'default-write'=>61,'login'=>1,'wp-skip'=>299,'wp-write'=>301,'filtered'=>5,'race'=>61,default=>throw new RuntimeException('activity mode')};$seed_time=time();$GLOBALS['modern_meta'][17]['wc_last_active']=(string)($seed_time-$ago);modern_metadata_checkpoint();$clock_before=time();$before=$GLOBALS['modern_meta'][17]['wc_last_active'];
  if('filtered'===$mode){add_filter('woocommerce_update_user_last_active_threshold',fn()=>10);}
  if('race'===$mode){$GLOBALS['modern_race']=true;}
  if('login'===$mode){add_action('wp_login',fn()=>wc_update_user_last_active(17));do_action('wp_login','synthetic',new WP_User(17));}
  elseif(str_starts_with($mode,'wp-')){add_action('wp',fn()=>wc_update_user_last_active(17));do_action('wp');}else{wc_update_user_last_active(17);}
  $writes=count(array_filter(HandlerContractBoundary::$events,fn($e)=>'meta-write'===$e['kind']&&'wc_last_active'===($e['identity']['key']??null)));modern_expect($writes===(in_array($mode,['default-write','login','wp-write'],true)?1:0),'threshold effect');
  if('race'===$mode){modern_expect('race-winner'===$GLOBALS['modern_meta'][17]['wc_last_active'],'race preservation');}
  if($writes){$attempt=array_values(array_filter(HandlerContractBoundary::$events,fn($e)=>'meta-attempt'===$e['kind']))[0]['identity'];modern_expect($attempt['previous']===$before,'previous-value conditional write');}
  $attempts=array_values(array_filter(HandlerContractBoundary::$events,fn($e)=>'meta-attempt'===$e['kind']&&'wc_last_active'===$e['identity']['key']));modern_finish(['mode'=>$mode,'seed_time'=>$seed_time,'seed_ago'=>$ago,'clock_before'=>$clock_before,'clock_after'=>time(),'activity_value'=>$attempts[0]['identity']['submitted']??null]);return;
 }
 if('session-store'===$case || 'customer-store'===$case){
  // Real parent session storage, with no native init or cookie transport.
  WC()->session=new WC_Session_Handler();$customer=new WC_Customer();$customer->set_id(17);$customer->set_object_read(true);$customer->set_billing_country('PT');$customer->set_shipping_country('PT');$customer->set_billing_city('account-city');$customer->set_billing_address_1('account-address');$customer->apply_changes();
  $store=new WC_Customer_Data_Store_Session();
  if('session-store'===$case){
   WC()->session->set('customer',['id'=>'17','date_modified'=>'','city'=>'','address_1'=>"O'Reilly\\lane"]);$store->read($customer);modern_expect(''===$customer->get_billing_city() && "O'Reilly\\lane"===$customer->get_billing_address_1(),'explicit clearing/no unslash');
   $customer->set_billing_city('missing-stays');WC()->session->set('customer',['id'=>'17','date_modified'=>'']);$store->read($customer);modern_expect('missing-stays'===$customer->get_billing_city(),'missing field preserved');
   WC()->session->set('customer',['id'=>'0','date_modified'=>'','city'=>'stale-guest']);$store->read($customer);modern_expect('missing-stays'===$customer->get_billing_city(),'actor mismatch excludes guest');
   $store->save_to_session($customer);modern_expect('missing-stays'===WC()->session->get('customer')['city'],'ordinary save control');modern_finish();return;
  }
  $v="O'Reilly\\lane";$customer->set_billing_address_1($v);$customer->set_billing_city($v);$nativeStore=new WC_Customer_Data_Store();
  // Real inherited save invokes the genuine account datastore update, followed by genuine read.
  $customer->save();$reread=new WC_Customer(17);modern_expect($v===$reread->get_billing_city()&&$v===$reread->get_billing_address_1(),'native customer save/read roundtrip');
  modern_expect($v===get_user_meta(17,'billing_city',true)&&$v===get_user_meta(17,'billing_address_1',true),'native customer slash roundtrip');modern_expect($GLOBALS['modern_meta'][17]['_woocommerce_persistent_cart_1']===$initial_meta[17]['_woocommerce_persistent_cart_1'],'unrelated metadata preserved');modern_finish();return;
 }
 // Explicit fixture cohort derives only from artifact-verified literal profile entries.
 $profile=json_decode(file_get_contents(__DIR__.'/profile.json'),true,512,JSON_THROW_ON_ERROR);
 $map=['WP_Hook'=>'wordpress/wp-includes/class-wp-hook.php','WC_Customer'=>'woocommerce/includes/class-wc-customer.php','WC_Cart'=>'woocommerce/includes/class-wc-cart.php','WC_Cart_Session'=>'woocommerce/includes/class-wc-cart-session.php','WC_Payment_Gateways'=>'woocommerce/includes/class-wc-payment-gateways.php'];
 $sources=[];foreach($map as$class=>$path){$sources[$class]=$profile['files'][$path];}
 foreach(['WPGraphQL\\Router'=>__DIR__.'/boundaries.php',QL_Session_Handler::class=>$owner.'/includes/utils/class-ql-session-handler.php',Cart_Session_Lifecycle::class=>$owner.'/includes/utils/class-cart-session-lifecycle.php',\WPGraphQL\WooCommerce\Utils\Cart_Session_Operation::class=>$owner.'/includes/utils/class-cart-session-operation.php',\GraphQL\Executor\ExecutionResult::class=>$gql.'/vendor/webonyx/graphql-php/src/Executor/ExecutionResult.php']as$class=>$file){$sources[$class]=$profile['files'][substr($file,strlen($root)+1)]??$profile['fixture_files'][basename($file)]??$profile['owned_files'][$file];}
 foreach([\WPGraphQL\Login\Mutation\RefreshToken::class,\WPGraphQL\Login\Auth\TokenManager::class,\WPGraphQL\Login\Auth\User::class,\WPGraphQL\Login\Utils\Utils::class,\WPGraphQL\Login\Vendor\Firebase\JWT\JWT::class,\WPGraphQL\Login\Vendor\Firebase\JWT\Key::class]as$class){$f=(new ReflectionClass($class))->getFileName();$sources[$class]=$profile['files'][substr($f,strlen($root)+1)];}
 if('refresh-wrong-source'===$case){$sources[\WPGraphQL\Login\Auth\TokenManager::class]=str_repeat('0',64);}
 if('source-wrong'===$case){$sources['WC_Customer']=str_repeat('0',64);}if('source-missing'===$case){unset($sources['WC_Cart']);}
 define('WOOGRAPHQL_CART_SESSION_SOURCE_COHORT',$sources);
 $callbackManifest=[
 ['hook'=>'graphql_mutation_input','kind'=>'function','function'=>'modern_refresh_input','priority'=>10,'accepted_args'=>4,'stable_registry'=>true,'nonstreaming'=>true,'sha256'=>$profile['fixture_files']['callbacks.php']],
 ['hook'=>'graphql_mutation_payload','kind'=>'function','function'=>'modern_refresh_payload','priority'=>10,'accepted_args'=>5,'stable_registry'=>true,'nonstreaming'=>true,'sha256'=>$profile['fixture_files']['callbacks.php']],
 ['hook'=>'woocommerce_payment_complete_order_status','kind'=>'method','class'=>'WC_Gateway_COD','method'=>'change_payment_complete_order_status','instance'=>true,'priority'=>10,'accepted_args'=>3,'stable_registry'=>true,'nonstreaming'=>true,'sha256'=>$profile['files']['woocommerce/includes/gateways/cod/class-wc-gateway-cod.php']],
 ['hook'=>'woocommerce_payment_complete','kind'=>'function','function'=>'wc_paying_customer','priority'=>10,'accepted_args'=>1,'stable_registry'=>true,'nonstreaming'=>true,'sha256'=>$profile['files']['woocommerce/includes/wc-user-functions.php']],
 ['hook'=>'wc_payment_gateways_initialized','kind'=>'method','class'=>'WC_Payment_Gateways','method'=>'on_payment_gateways_initialized','instance'=>true,'priority'=>10,'accepted_args'=>1,'stable_registry'=>true,'nonstreaming'=>true,'sha256'=>$sources['WC_Payment_Gateways']],
 ];if('unreviewed-gateway'===$case){$callbackManifest=array_values(array_filter($callbackManifest,fn($record)=>($record['class']??null)!=='WC_Gateway_COD'));}define('WOOGRAPHQL_CART_SESSION_CALLBACK_COHORT',$callbackManifest);
 $seedParent=new WC_Session_Handler();$guest='t_'.str_repeat('a',30);$exp=(string)(time()+86400);$expiring=(string)(time()+3600);$hash=(new ReflectionMethod(WC_Session_Handler::class,'hash'))->invoke($seedParent,$guest.'|'.$exp);$_COOKIE['wp_woocommerce_session_'.COOKIEHASH]=$guest.'|'.$exp.'|'.$expiring.'|'.$hash;

 if('fresh-viewer'===$case){$_SERVER['HTTP_AUTHORIZATION']='Bearer '.getenv('WL_MODERN_AUTH_BEARER');HandlerContractBoundary::$user=\WPGraphQL\Login\Auth\ServerAuthentication::instance()->determine_current_user(0);unset($_COOKIE['wp_woocommerce_session_'.COOKIEHASH]);}
 if('invalid-cart-token'===$case){$_SERVER['HTTP_WOOCOMMERCE_SESSION']='Session invalid';}
 if('retired-cart-token'===$case){HandlerContractBoundary::$user=0;$guestId=str_repeat('a',32);HandlerContractBoundary::$rows[$guestId]=['cart'=>['retired-sentinel'=>true]];$token=\WPGraphQL\WooCommerce\Vendor\Firebase\JWT\JWT::encode(['iss'=>get_bloginfo('url'),'iat'=>time()-5,'nbf'=>time()-5,'exp'=>time()+86400,'data'=>['customer_id'=>$guestId]],GRAPHQL_WOOCOMMERCE_SECRET_KEY,'HS256');$_SERVER['HTTP_WOOCOMMERCE_SESSION']='Session '.$token;$tuple='';foreach([DB_NAME,'contract_woocommerce_sessions',$guestId]as$part){$tuple.=strlen($part).':'.$part;}$hash=hash('sha256',$tuple);HandlerContractBoundary::$markers['wl_cart_retired_v1_'.$hash]=json_encode(['schema'=>1,'kind'=>'checkout_guest_retirement','source_tuple_sha256'=>$hash,'destination_tuple_sha256'=>str_repeat('b',64),'operation_uuid'=>'11111111-1111-4111-8111-111111111111']);$GLOBALS['modern_markers_before']=HandlerContractBoundary::$markers;}
 $h=new QL_Session_Handler();$GLOBALS['modern_handler']=$h;WC()->session=$h;
 if('source-tampered'===$case){$GLOBALS['modern_success']=true;$GLOBALS['modern_do_shutdown']=true;}
 if(in_array($case,['source-wrong','source-missing'],true)){modern_refused(function()use($h){$h->init();$h->assert_session_ready();});if($h->get_owned_lifecycle()){$h->get_owned_lifecycle()->cleanup();}while(ob_get_level()){ob_end_clean();}restore_exception_handler();modern_finish();return;}
 $h->init();
 if(in_array($case,['source-wrong','source-missing'],true)){modern_refused(fn()=>$h->assert_session_ready());$h->get_owned_lifecycle()->cleanup();modern_finish();return;}
 if(in_array($case,['invalid-cart-token','retired-cart-token'],true)){modern_refused(fn()=>$h->assert_session_ready(),'WL_CART_SESSION_INVALID');$life=$h->get_owned_lifecycle();$h->init_session_cookie();$h->set_customer_session_cookie(true);$h->save_data();$life->cleanup();modern_expect(0===$db->writes&&0===$db->reads,'invalid/retired before hydration');modern_finish();return;}
 $h->assert_session_ready();
 if(in_array($case,['ordinary-flush','detached'],true)){$_COOKIE['woocommerce_items_in_cart']='1';$_COOKIE['woocommerce_cart_hash']='sentinel';}
 add_action('woocommerce_before_customer_object_save',static function(){modern_event('customer.save');},10,0);add_action('woocommerce_cart_updated',static function(){modern_event('cart.set_session');},10,0);add_action('woocommerce_set_cart_cookies',static function(){modern_event('cart.cookies');},20,0);
 WC()->customer=new WC_Customer(get_current_user_id(),true);add_action('shutdown',[WC()->customer,'save'],10,0);WC()->cart=new WC_Cart();
 $life=$h->get_owned_lifecycle();if(str_starts_with($case,'refresh-')){add_filter('graphql_mutation_input','modern_refresh_input',10,4);add_filter('graphql_mutation_payload','modern_refresh_payload',10,5);}
 if(in_array($case,['gateway-prime-owned-throw','gateway-prime-generic-throw'],true)){$GLOBALS['modern_success']=true;$GLOBALS['modern_do_shutdown']=true;}
 $cartSession=(new ReflectionProperty(WC_Cart::class,'session'))->getValue(WC()->cart);if(in_array($case,['ordinary-flush','ordinary-probe','fresh-viewer'],true)){do_action('wp_loaded');}if('unreviewed-gateway'===$case){modern_refused(fn()=>do_action('do_graphql_request'));$life->cleanup();modern_finish();return;}do_action('do_graphql_request');
 modern_expect('WC_Data'===(new ReflectionMethod(WC_Customer::class,'save'))->getDeclaringClass()->getName(),'genuine inherited customer save');modern_expect('WC_Session_Handler'===(new ReflectionClass($h))->getParentClass()->getName(),'genuine inherited session parent');modern_expect(null!==(new ReflectionProperty(Cart_Session_Lifecycle::class,'frozen'))->getValue($life),'native gateway registration frozen');
 modern_expect((new ReflectionProperty(WC_Cart_Session::class,'cart'))->getValue($cartSession)===WC()->cart,'captured cart back-reference');
 modern_expect(false!==has_action('shutdown',[WC()->customer,'save'])&&0===has_action('shutdown',[$cartSession,'maybe_set_cart_cookies']),'actual writers registered');
 $primes=array_values(array_filter(HandlerContractBoundary::$events,fn($e)=>'option-prime'===$e['kind']));modern_expect(1===count($primes)&&['woocommerce_bacs_settings','woocommerce_bacs_accounts','woocommerce_cheque_settings','woocommerce_cod_settings','woocommerce_paypal_settings']===$primes[0]['identity'],'exact five options primed');
 modern_expect(4===count(WC_Payment_Gateways::instance()->payment_gateways),'genuine built-in gateways loaded');
 if('objects'===$case){$life->cleanup();modern_finish(['gateways'=>array_map('get_class',WC_Payment_Gateways::instance()->payment_gateways)]);return;}
 if('receiver-backreference'===$case){(new ReflectionProperty(WC_Cart_Session::class,'cart'))->setValue($cartSession,clone WC()->cart);modern_refused(fn()=>$life->guard_created_objects());$life->cleanup();modern_finish();return;}
 if('receiver-cart'===$case){WC()->cart=clone WC()->cart;modern_refused(fn()=>$life->guard_created_objects());$life->cleanup();modern_finish();return;}
 if('receiver-customer'===$case){WC()->customer=new WC_Customer(17,true);modern_refused(fn()=>$life->guard_created_objects());$life->cleanup();modern_finish();return;}
 if(in_array($case,['gateway-arity','gateway-priority','gateway-receiver'],true)){
  $manager=WC_Payment_Gateways::instance();remove_action('wc_payment_gateways_initialized',[$manager,'on_payment_gateways_initialized'],10);$receiver='gateway-receiver'===$case?(new ReflectionClass(WC_Payment_Gateways::class))->newInstanceWithoutConstructor():$manager;add_action('wc_payment_gateways_initialized',[$receiver,'on_payment_gateways_initialized'],'gateway-priority'===$case?11:10,'gateway-arity'===$case?2:1);modern_refused(fn()=>$life->guard_request());$life->cleanup();modern_finish();return;
 }
 if('late-hook'===$case){add_filter('graphql_mutation_input',fn($x)=>$x,20,4);modern_refused(fn()=>$life->guard_request());$life->cleanup();modern_finish();return;}
 if(str_starts_with($case,'refresh-') || 'fresh-viewer'===$case){require __DIR__.'/graphql.php';$response=modern_refresh_execute($case);$GLOBALS['modern_do_shutdown']=true;$GLOBALS['modern_success']=true;$GLOBALS['modern_detail']=['actor'=>get_current_user_id(),'starting_actor'=>$GLOBALS['modern_starting_actor'],'detached'=>$h->is_auth_detached(),'detached_before_identity'=>$GLOBALS['modern_detached_before_identity']??null,'carried_cart_header'=>isset($_SERVER['HTTP_WOOCOMMERCE_SESSION'])];do_action('graphql_process_http_request_response',$response,null,null,null,null,200);}
 if('ordinary-probe'===$case){WC()->customer->save();$cartSession->set_session();$cartSession->persistent_cart_update();$cartSession->maybe_set_cart_cookies();$life->cleanup();modern_finish();return;}
 if('ordinary-flush'===$case){modern_event('flush.start');$h->prepare_session_token();$h->complete_session_preparation();$GLOBALS['modern_success']=true;$GLOBALS['modern_do_shutdown']=true;do_action('graphql_process_http_request_response',['data'=>['ok'=>true]],null,null,null,null,200);}
 if(in_array($case,['detached','absent-cart-token'],true)){$h->init_session_cookie();$h->detach_for_auth();$h->init_session_cookie();$h->set_customer_session_cookie(true);$h->update_session_timestamp($guest,time()+9999);$h->save_data();$GLOBALS['modern_do_shutdown']=true;$GLOBALS['modern_success']=true;do_action('graphql_process_http_request_response',['data'=>['ok'=>true]],null,null,null,null,200);}
 throw new RuntimeException('case unavailable');
}catch(Throwable$e){if(in_array($case,['gateway-prime-owned-throw','gateway-prime-generic-throw','source-tampered'],true)){throw $e;}
 $GLOBALS['modern_error']=get_class($e).': '.$e->getMessage().' at '.basename($e->getFile()).':'.$e->getLine();if(isset($life)){$life->cleanup();}fwrite(STDERR,$GLOBALS['modern_error']."\n");exit(1);}
